[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "About"
  pageRef = "about"
  weight = 20

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/pedromaca"
  weight = 400